// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package lqwd_node

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	SpawnNodes(ctx context.Context, in *NodeDetails, opts ...grpc.CallOption) (*Node, error)
	GetNodesListByStatus(ctx context.Context, in *Status, opts ...grpc.CallOption) (*Node, error)
	DestroyNode(ctx context.Context, in *NodeId, opts ...grpc.CallOption) (*Node, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) SpawnNodes(ctx context.Context, in *NodeDetails, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/node.NodeService/SpawnNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNodesListByStatus(ctx context.Context, in *Status, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/node.NodeService/GetNodesListByStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DestroyNode(ctx context.Context, in *NodeId, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/node.NodeService/DestroyNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility
type NodeServiceServer interface {
	SpawnNodes(context.Context, *NodeDetails) (*Node, error)
	GetNodesListByStatus(context.Context, *Status) (*Node, error)
	DestroyNode(context.Context, *NodeId) (*Node, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (UnimplementedNodeServiceServer) SpawnNodes(context.Context, *NodeDetails) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpawnNodes not implemented")
}
func (UnimplementedNodeServiceServer) GetNodesListByStatus(context.Context, *Status) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodesListByStatus not implemented")
}
func (UnimplementedNodeServiceServer) DestroyNode(context.Context, *NodeId) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyNode not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_SpawnNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SpawnNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.NodeService/SpawnNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SpawnNodes(ctx, req.(*NodeDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNodesListByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Status)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodesListByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.NodeService/GetNodesListByStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodesListByStatus(ctx, req.(*Status))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DestroyNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DestroyNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.NodeService/DestroyNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DestroyNode(ctx, req.(*NodeId))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpawnNodes",
			Handler:    _NodeService_SpawnNodes_Handler,
		},
		{
			MethodName: "GetNodesListByStatus",
			Handler:    _NodeService_GetNodesListByStatus_Handler,
		},
		{
			MethodName: "DestroyNode",
			Handler:    _NodeService_DestroyNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lqwd_node/node.proto",
}
