// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: lqwd_node/node.proto

package lqwd_node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeDetails_Status int32

const (
	NodeDetails_RUNNING NodeDetails_Status = 0
	NodeDetails_FAILED  NodeDetails_Status = 1
)

// Enum value maps for NodeDetails_Status.
var (
	NodeDetails_Status_name = map[int32]string{
		0: "RUNNING",
		1: "FAILED",
	}
	NodeDetails_Status_value = map[string]int32{
		"RUNNING": 0,
		"FAILED":  1,
	}
)

func (x NodeDetails_Status) Enum() *NodeDetails_Status {
	p := new(NodeDetails_Status)
	*p = x
	return p
}

func (x NodeDetails_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeDetails_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_lqwd_node_node_proto_enumTypes[0].Descriptor()
}

func (NodeDetails_Status) Type() protoreflect.EnumType {
	return &file_lqwd_node_node_proto_enumTypes[0]
}

func (x NodeDetails_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeDetails_Status.Descriptor instead.
func (NodeDetails_Status) EnumDescriptor() ([]byte, []int) {
	return file_lqwd_node_node_proto_rawDescGZIP(), []int{0, 0}
}

type Status_Status int32

const (
	Status_RUNNING Status_Status = 0
	Status_FAILED  Status_Status = 1
)

// Enum value maps for Status_Status.
var (
	Status_Status_name = map[int32]string{
		0: "RUNNING",
		1: "FAILED",
	}
	Status_Status_value = map[string]int32{
		"RUNNING": 0,
		"FAILED":  1,
	}
)

func (x Status_Status) Enum() *Status_Status {
	p := new(Status_Status)
	*p = x
	return p
}

func (x Status_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_lqwd_node_node_proto_enumTypes[1].Descriptor()
}

func (Status_Status) Type() protoreflect.EnumType {
	return &file_lqwd_node_node_proto_enumTypes[1]
}

func (x Status_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status_Status.Descriptor instead.
func (Status_Status) EnumDescriptor() ([]byte, []int) {
	return file_lqwd_node_node_proto_rawDescGZIP(), []int{1, 0}
}

type Node_Status int32

const (
	Node_RUNNING Node_Status = 0
	Node_FAILED  Node_Status = 1
)

// Enum value maps for Node_Status.
var (
	Node_Status_name = map[int32]string{
		0: "RUNNING",
		1: "FAILED",
	}
	Node_Status_value = map[string]int32{
		"RUNNING": 0,
		"FAILED":  1,
	}
)

func (x Node_Status) Enum() *Node_Status {
	p := new(Node_Status)
	*p = x
	return p
}

func (x Node_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Node_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_lqwd_node_node_proto_enumTypes[2].Descriptor()
}

func (Node_Status) Type() protoreflect.EnumType {
	return &file_lqwd_node_node_proto_enumTypes[2]
}

func (x Node_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Node_Status.Descriptor instead.
func (Node_Status) EnumDescriptor() ([]byte, []int) {
	return file_lqwd_node_node_proto_rawDescGZIP(), []int{3, 0}
}

type NodeDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName  string              `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	Ip        string              `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	UserId    string              `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Status    *NodeDetails_Status `protobuf:"varint,4,opt,name=status,proto3,enum=node.NodeDetails_Status,oneof" json:"status,omitempty"`
	CreatedAt string              `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *NodeDetails) Reset() {
	*x = NodeDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lqwd_node_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDetails) ProtoMessage() {}

func (x *NodeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_lqwd_node_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDetails.ProtoReflect.Descriptor instead.
func (*NodeDetails) Descriptor() ([]byte, []int) {
	return file_lqwd_node_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeDetails) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeDetails) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeDetails) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NodeDetails) GetStatus() NodeDetails_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return NodeDetails_RUNNING
}

func (x *NodeDetails) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status_Status `protobuf:"varint,4,opt,name=status,proto3,enum=node.Status_Status,oneof" json:"status,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lqwd_node_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_lqwd_node_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_lqwd_node_node_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetStatus() Status_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Status_RUNNING
}

type NodeId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
}

func (x *NodeId) Reset() {
	*x = NodeId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lqwd_node_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeId) ProtoMessage() {}

func (x *NodeId) ProtoReflect() protoreflect.Message {
	mi := &file_lqwd_node_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeId.ProtoReflect.Descriptor instead.
func (*NodeId) Descriptor() ([]byte, []int) {
	return file_lqwd_node_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeId) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName  string       `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	Ip        string       `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	UserId    string       `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Status    *Node_Status `protobuf:"varint,4,opt,name=status,proto3,enum=node.Node_Status,oneof" json:"status,omitempty"`
	CreatedAt string       `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Id        string       `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lqwd_node_node_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_lqwd_node_node_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_lqwd_node_node_proto_rawDescGZIP(), []int{3}
}

func (x *Node) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Node) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Node) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Node) GetStatus() Node_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Node_RUNNING
}

func (x *Node) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_lqwd_node_node_proto protoreflect.FileDescriptor

var file_lqwd_node_node_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6c, 0x71, 0x77, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0xd4, 0x01, 0x0a,
	0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x21, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x68, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x22,
	0x21, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44,
	0x10, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x20, 0x0a,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22,
	0xd6, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x95, 0x01, 0x0a, 0x0b, 0x4e, 0x6f, 0x64,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x53, 0x70, 0x61, 0x77,
	0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x0a, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x0a, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0c, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x1a, 0x0a, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x42, 0x1e, 0x5a, 0x1c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x71, 0x77,
	0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x3b, 0x6c, 0x71, 0x77, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lqwd_node_node_proto_rawDescOnce sync.Once
	file_lqwd_node_node_proto_rawDescData = file_lqwd_node_node_proto_rawDesc
)

func file_lqwd_node_node_proto_rawDescGZIP() []byte {
	file_lqwd_node_node_proto_rawDescOnce.Do(func() {
		file_lqwd_node_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_lqwd_node_node_proto_rawDescData)
	})
	return file_lqwd_node_node_proto_rawDescData
}

var file_lqwd_node_node_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_lqwd_node_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lqwd_node_node_proto_goTypes = []interface{}{
	(NodeDetails_Status)(0), // 0: node.nodeDetails.Status
	(Status_Status)(0),      // 1: node.Status.Status
	(Node_Status)(0),        // 2: node.Node.Status
	(*NodeDetails)(nil),     // 3: node.nodeDetails
	(*Status)(nil),          // 4: node.Status
	(*NodeId)(nil),          // 5: node.nodeId
	(*Node)(nil),            // 6: node.Node
}
var file_lqwd_node_node_proto_depIdxs = []int32{
	0, // 0: node.nodeDetails.status:type_name -> node.nodeDetails.Status
	1, // 1: node.Status.status:type_name -> node.Status.Status
	2, // 2: node.Node.status:type_name -> node.Node.Status
	3, // 3: node.NodeService.SpawnNodes:input_type -> node.nodeDetails
	4, // 4: node.NodeService.GetNodesListByStatus:input_type -> node.Status
	5, // 5: node.NodeService.DestroyNode:input_type -> node.nodeId
	6, // 6: node.NodeService.SpawnNodes:output_type -> node.Node
	6, // 7: node.NodeService.GetNodesListByStatus:output_type -> node.Node
	6, // 8: node.NodeService.DestroyNode:output_type -> node.Node
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_lqwd_node_node_proto_init() }
func file_lqwd_node_node_proto_init() {
	if File_lqwd_node_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lqwd_node_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lqwd_node_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lqwd_node_node_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lqwd_node_node_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lqwd_node_node_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_lqwd_node_node_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_lqwd_node_node_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lqwd_node_node_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lqwd_node_node_proto_goTypes,
		DependencyIndexes: file_lqwd_node_node_proto_depIdxs,
		EnumInfos:         file_lqwd_node_node_proto_enumTypes,
		MessageInfos:      file_lqwd_node_node_proto_msgTypes,
	}.Build()
	File_lqwd_node_node_proto = out.File
	file_lqwd_node_node_proto_rawDesc = nil
	file_lqwd_node_node_proto_goTypes = nil
	file_lqwd_node_node_proto_depIdxs = nil
}
